"""Shared test fixtures.

Fixtures on disk are generated by ``scripts/generate_fixtures.py`` and are
regenerated automatically if missing, so a fresh checkout can run the suite
with no manual step.
"""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

import pytest

SERVICE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = SERVICE_ROOT.parents[1]
FIXTURE_DIR = REPO_ROOT / "fixtures" / "generated"

sys.path.insert(0, str(SERVICE_ROOT))

from app.config import Settings  # noqa: E402
from app.conversion.engine import ConversionEngine  # noqa: E402
from app.ocr.service import OcrService  # noqa: E402

# Fixtures that must exist before the suite can run.
REQUIRED_FIXTURES = ("text.pdf", "ocr-english.png", "table.csv")


def _ensure_fixtures() -> None:
    if all((FIXTURE_DIR / name).is_file() for name in REQUIRED_FIXTURES):
        return
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "generate_fixtures.py")],
        check=True,
        cwd=REPO_ROOT,
    )


@pytest.fixture(scope="session", autouse=True)
def fixtures_available() -> None:
    _ensure_fixtures()


@pytest.fixture(scope="session")
def fixture_dir() -> Path:
    return FIXTURE_DIR


@pytest.fixture
def fixture(fixture_dir: Path):
    """Return a fixture path, skipping the test if it was not generated."""

    def _get(name: str) -> Path:
        path = fixture_dir / name
        if not path.is_file():
            pytest.skip(f"fixture {name} is not available")
        return path

    return _get


@pytest.fixture
def settings(tmp_path: Path) -> Settings:
    """Settings pointed at an isolated workspace, with limits kept small."""
    return Settings(
        app_env="test",
        workspace_root=tmp_path / "workspace",
        session_ttl_minutes=30,
        max_file_size_mb=10,
        max_total_upload_mb=25,
        max_files_per_job=10,
        max_archive_files=20,
        max_archive_uncompressed_mb=20,
        rate_limit_enabled=False,
        max_conversion_time_seconds=120,
        # Inherited from the environment so the suite works on machines where
        # Tesseract is not on PATH.
        tesseract_cmd=Settings().tesseract_cmd,
        tessdata_prefix=Settings().tessdata_prefix,
    )


@pytest.fixture
def ocr_service(settings: Settings) -> OcrService:
    return OcrService(settings)


@pytest.fixture
def engine(settings: Settings) -> ConversionEngine:
    return ConversionEngine(settings)


@pytest.fixture
def workdir(tmp_path: Path) -> Iterator[Path]:
    path = tmp_path / "work"
    path.mkdir(parents=True, exist_ok=True)
    yield path


def requires_ocr(service: OcrService) -> None:
    """Skip a test when no OCR provider is installed on this machine."""
    if not service.is_available():
        pytest.skip("no OCR provider available (Tesseract not installed)")
